### ISSUE TITLE
Can't find module `past`

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/hyppo#423]
graspologic builds are failing with 

```pytb
________________ ERROR collecting tests/cluster/test_autogmm.py ________________
ImportError while importing test module '/home/runner/work/graspologic/graspologic/tests/cluster/test_autogmm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.[20](https://github.com/graspologic-org/graspologic/actions/runs/12254240467/job/34184712749?pr=1093#step:6:21)/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cluster/test_autogmm.py:11: in <module>
    from graspologic.cluster.autogmm import AutoGMMCluster
graspologic/__init__.py:8: in <module>
    import graspologic.inference
graspologic/inference/__init__.py:6: in <module>
    from .latent_distribution_test import latent_distribution_test
graspologic/inference/latent_distribution_test.py:7: in <module>
    from hyppo.ksample import KSample
../../../.cache/pypoetry/virtualenvs/graspologic-pkHfzCJ8-py3.9/lib/python3.9/site-packages/hyppo/__init__.py:5: in <module>
    import hyppo.kgof
../../../.cache/pypoetry/virtualenvs/graspologic-pkHfzCJ8-py3.9/lib/python3.9/site-packages/hyppo/kgof/__init__.py:2: in <module>
    from .fssd import FSSD, FSSDH0SimCovObs
../../../.cache/pypoetry/virtualenvs/graspologic-pkHfzCJ8-py3.9/lib/python3.9/site-packages/hyppo/kgof/fssd.py:4: in <module>
    from past.utils import old_div
E   ModuleNotFoundError: No module named 'past'
```

I think it is missing from the dependencies

**Comment by sampan501** [comment]
Which `hyppo` version is being used? I believe this was fixed in #420 with v0.5.0

**Comment by bdpedigo** [comment]
hmm I'm somehow still seeing it despite having 0.5.1 installed:

`poetry show hyppo`
```
 name         : hyppo                                        
 version      : 0.5.1                                        
 description  : A comprehensive independence testing package 

dependencies
 - autograd >=1.3
 - numba >=0.46
 - numpy >=1.17
 - scikit-learn >=0.19.1
 - scipy >=1.4.0
```

**Comment by manuelarceaguirre** [comment]
Hi @bdpedigo @sampan501, I’ve opened a PR to fix the `past` dependency in `fssd.py` and `test_density.py`. Replaced `old_div` with `/` and used integer division in `simulate_null_dist` to resolve test failures. All 12 tests in `hyppo/kgof/tests/` pass locally on Python 3.12.

**Comment by ebridge2** [comment]
@sampan501 `future` is not listed in [setup.py](https://github.com/neurodata/hyppo/blob/875a4b3db12cd1afb8e52eab8da05e03dc615d2b/setup.py#L28) file is causing issues with installing from github, anyways. I would assume since you use the setup.py to create the distribution package for pypi, pypi would never know about this dependency even though it's listed in the requirements.txt, so if you install from pip it will never work unless you already have future, right?
